name: Build MediaSpider

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with PyAppify
        uses: ok-oldking/pyappify-action@v1
        with:
          config: pyappify.yml

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            */*.zip
